MODULE_HEAD : &HEAD CHID=[[V]], TITLE=[[V]] /
MODULE_MESH : &MESH ID=[[V]], IJK=[[V]], XB=[[V]] /
MODULE_TIME : &TIME T_BEGIN=[[V]], T_END=[[V]] /

MODULE_OBST : &OBST XB=[[V]], SURF_ID=[[C]] /
MODULE_SURF : &SURF ID=[[V]], HRRPUA=[[V]], MATL_ID=[[C]], NEAR_WALL_EDDY_VISCOSITY=[[V]]/
MODULE_VENT : &VENT SURF_ID=[[C]] /

MODULE_MATL : &MATL ID=[[V]] /
MODULE_REAC : &REAC ID=[[V]], FUEL=[[C]] /

MODULE_TAIL : &TAIL /

