MODULE_HEAD : &HEAD CHID=[[V]], TITLE=[[V]] /

MODULE_MESH : &MESH IJK=[[V]], XB=[[V]] /

MODULE_TIME : &TIME T_BEGIN=[[V]],T_END=[[V]],DT=[[V]],LOCK_TIME_STEP=[[C]] /

MODULE_MISC : &MISC GVEC=[[V]],  SMOKE3D_16=[[V]],
AEROSOL_AL2O3=[[C]],AEROSOL_SCRUBBING=[[C]],
AGGLOMERATION=[[C]],ALLOW_UNDERSIDE_PARTICLES=[[C]],
BNDF_DEFAULT=[[C]],CONSTANT_SPECIFIC_HEAT_RATIO=[[C]],
DEPOSITION=[[C]],FREEZE_VELOCITY=[[C]],GAMMA=[[V]],
GRAVITATIONAL_DEPOSITION=[[C]],GRAVITATIONAL_SETTLING=[[C]],
H_F_REFERENCE_TEMPERATURE=[[V]],HUMIDITY=[[V]],HVAC_MASS_TRANSPORT_CELL_L=[[C]],
IBLANK_SMV=[[C]],I_MAX_TEMP=[[V]],LEVEL_SET_ELLIPSE=[[C]],MAXIMUM_VISIBILITY=[[V]],
MINIMUM_FILM_THICKNESS=[[V]], MPI_TIMEOUT=[[V]],NOISE=[[C]],NOISE_VELOCITY=[[V]],
NO_PRESSURE_ZONES=[[C]],OVERWRITE=[[C]],PARTICLE_CFL=[[C]], POROUS_FLOOR=[[C]],PR=[[V]],
P_INF=[[V]],SC=[[V]],SHARED_FILE_SYSTEM=[[C]],SIMULATION_MODE=[[V]],SOLID_PHASE_ONLY=[[C]],
THERMOPHORETIC_DEPOSITION=[[C]],THERMOPHORETIC_SETTLING=[[C]],TMPA=[[V]], TURBULENT_DEPOSITION=[[C]],VERBOSE=[[C]] /

MODULE_INIT : &INIT XB=[[V]],TEMPERATURE=[[V]],DENSITY=[[V]],SPEC_ID=[[V]],
MASS_FRACTION=[[V]],VOLUME_FRACTION=[[V]],HRRPUV=[[V]],RADIATIVE_FRACTION=[[V]] /

MODULE_VENT : &VENT MB=[[V]], SURF_ID=[[V]],OUTLINE=[[C]] /

MODULE_HAVC : &HAVC TYPE_ID=[[C]],ID=[[V]],MAX_FLOW=[[V]],MAX_PRESSURE=[[V]],TAU_FAN=[[V]],VOLUME_FLOW=[[V]],XYZ=[[V]],LOSS=[[V]],DIAMETER=[[V]] /

MODULE_REAC : &REAC FUEL=[[V]],AUTO_IGNITION_TEMPERATURE=[[V]],SETPOINT=[[V]] /

MODULE_SURF : &SURF ID=[[V]], MATL_ID=MODULE_MATL.ID,ADIABATIC=[[C]],
AREA_MULTIPLIER=[[V]],BACKING=[[V]],BURN_AWAY=[[C]],BURN_DURATION=[[V]],CELL_SIZE_FACTOR=[[V]],
COLOR=[[V]],CONVECTION_LENGTH_SCALE=[[V]],CONVECTIVE_HEAT_FLUX=[[V]],CONVERT_VOLUME_TO_MASS=[[V]],
DEFAULT=[[C]],DELTA_TMP_MAX=[[V]],DRAG_COEFFICIENT=[[V]],DT_INSERT=[[V]],E_COEFFICIENT=[[V]],EMISSIVITY=[[V]],
EMISSIVITY_BACK=[[V]],EXTERNAL_FLUX=[[V]],EXTINCTION_TEMPERATURE=[[V]],FREE_SLIP=[[C]],GEOMETRY=[[V]],
HEAT_OF_VAPORIZATION=[[V]],HEAT_TRANSFER_COEFFICIENT=[[V]],HEAT_TRANSFER_COEFFICIENT_BACK=[[V]],
HEAT_TRANSFER_MODEL=[[C]],HRRPUA=[[V]],HT3D=[[C]],IGNITION_TEMPERATURE=[[V]],INNER_RADIUS=[[V]],
INTERNAL_HEAT_SOURCE=[[V]],MINIMUM_SCALING_HEAT_FLUX=[[V]],MAXIMUM_SCALING_HEAT_FLUX=[[V]],
MINIMUM_BURNOUT_TIME=[[V]],MINIMUM_LAYER_THICKNESS=[[V]],N_LAYER_CELLS_MAX=[[V]],NEAR_WALL_EDDY_VISCOSITY=[[V]],
NEAR_WALL_TURBULENCE_MODEL=[[C]],NET_HEAT_FLUX=[[V]],THICKNESS=[[V]] /

MODULE_MATL : &MATL ID=[[V]], CONDUCTIVITY=[[V]],DENSITY=[[V]],SPECIFIC_HEAT=[[V]],
ABSORPTION_COEFFICIENT=[[V]],ADJUST_H=[[C]],ALLOW_SHRINKING=[[C]],ALLOW_SWELLING=[[C]],
BOILING_TEMPERATURE=[[V]],EMISSIVITY=[[V]],SURFACE_OXIDATION_MODEL=[[C]] /

MODULE_RAMP : &RAMP /

MODULE_OBST : &OBST SURF_ID=MODULE_SURF.ID,BULK_DENSITY=[[V]],COLOR=[[V]],OUTLINE=[[C]],
OVERLAY=[[C]],PERMIT_HOLE=[[C]],REMOVABLE=[[C]],SHAPE=[[V]],THICKEN=[[C]],TRANSPARENCYT=[[V]] /

MODULE_GEOM : &GEOM SURF_ID=MODULE_SURF.ID,CYLINDER_LENGTH=[[V]],CYLINDER_RADIUS=[[V]],CYLINDER_ORIGIN=[[V]],
CYLINDER_AXIS=[[V]],CYLINDER_NSEG_AXIS=[[C]],CYLINDER_NSEG_THETA=[[C]] /

MODULE_PART : &PART DIAMETER=[[V]],ID=[[V]],AGE=[[V]],CHECK_DISTRIBUTION=[[C]],COLOR=[[V]],DRAG_LAW=[[V]],INITIAL_TEMPERATURE=[[V]],
SPEC_ID=[[V]],HORIZONTAL_VELOCITY=[[V]],VERTICAL_VELOCITY=[[V]],MAXIMUM_DIAMETER=[[V]],MINIMUM_DIAMETER=[[V]],
MONODISPERSE=[[C]],NEW_PARTICLE_INCRMENT=[[V]],DENSE_VOLUME_FRACTION=[[V]],SURF_ID=[[V]] /

MODULE_PROP : &PROP ACTIVATION_TEMPERATURE=[[V]],ID=[[V]],QUANTITY=[[V]],RTI=[[V]],C_FACTOR=[[V]],
INITIAL_TEMPERATURE=[[V]],FLOW_RATE=[[V]],MASS_FLOW_RATE=[[V]],OFFSET=[[V]],PARTICLE_VELOCITY=[[V]],
ORIFICE_DIAMETER=[[V]],SPRAY_ANGLE=[[V]],PART_ID=[[V]]/

MODULE_TAIL : &TAIL /

